services:
  webserver:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=nsustain.com
      - NGINX_PORT=443
    volumes:
      - ./index.html /usr/share/nginx/html/index.html
      - ./manifest.json /usr/share/nginx/html/manifest.json
      - ./img /usr/share/nginx/html/img
